Repository 4Subsea/smsfusion-python, pull requests merged in 2023-08, with the labels that each got.

#1 Setup initial empty package
  build.bat
  pyproject.toml
  src/smsfusion/__about__.py
  src/smsfusion/__init__.py
  src/smsfusion/_something.py
  tests/test_something.py
Labels: chore

#2 Add strapdown INS implementation
  pyproject.toml
  src/smsfusion/__init__.py
  src/smsfusion/_ins.py
  src/smsfusion/_something.py
  src/smsfusion/_transforms.py
  tests/test_ins.py
  tests/test_something.py
  tests/test_transforms.py
Labels: feature

#3 Add pull request template
  .github/pull_request_template.md
Labels: chore

#5 Add testing toolchain
  pyproject.toml
Labels: chore

#6 Setup Sphinx documentation
  .gitignore
  docs/_static/empty
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/function.rst
  docs/conf.py
  docs/index.rst
  docs/reference/index.rst
  docs/release_notes.rst
  pyproject.toml
Labels: documentation

#4 Set up CI GitHub workflow
  .github/workflows/ci.yml
  docs/conf.py
  pyproject.toml
Labels: chore

#7 Setup deploy workflow
  .github/release.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy_public.yaml
  .github/workflows/make_release.yaml
Labels: chore

#8 Set up deploy workflow - fix 1
  .github/workflows/deploy_public.yaml
  src/smsfusion/__about__.py
Labels: chore

#10 Deprecate Python 3.9 support
  .github/workflows/ci.yaml
  pyproject.toml
Labels: breaking-change

#9 Add type annotations and mypy
  pyproject.toml
  src/smsfusion/_ins.py
  src/smsfusion/_transforms.py
Labels: enhancement

#11 Implement AHRS (Mahony)
  pyproject.toml
  src/smsfusion/__init__.py
  src/smsfusion/_ahrs.py
  src/smsfusion/_ins.py
  src/smsfusion/_transforms.py
  src/smsfusion/_vectorops.py
  tests/test_ahrs.py
  tests/test_ins.py
  tests/test_transforms.py
  tests/test_vectorops.py
Labels: feature

#13 Inject release notes from GitHub
  .github/workflows/deploy_public.yaml
  docs/conf.py
  docs/index.rst
  docs/release_notes.rst
  docs/release_notes/generated.md
  docs/release_notes/index.rst
  pyproject.toml
Labels: chore

#14 Handle inputs to AHRS.update() more robustly
  src/smsfusion/_ahrs.py
  tests/test_ahrs.py
Labels: bug
