Repository 4Subsea/smsfusion-python, pull requests merged in 2023-09, with the labels that each got.

#16 Calculate unit quaternion from Euler angles
  src/smsfusion/_transforms.py
  tests/test_transforms.py
Labels: feature

#17 Ensure consistent transform convention
  src/smsfusion/_ins.py
  src/smsfusion/_transforms.py
  tests/test_ins.py
  tests/test_transforms.py
Labels: enhancement

#15 Aided INS system (w/ external AHRS)
  docs/reference/index.rst
  src/smsfusion/__init__.py
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: feature

#18 Make AHRS used in AidedINS configurable
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: feature

#21 Fix wrong rotation in AHRS update algorithm
  src/smsfusion/_ahrs.py
Labels: bug

#22 Allow irregular position aiding in `AidedINS`
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: enhancement
