Repository 4Subsea/smsfusion-python, pull requests merged in 2023-12, with the labels that each got.

#41 Strapdown algorithm using quaternions
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: breaking-change

#43 Enforce normalization of quaternions given to StrapdownINS.
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: enhancement

#40 Add private skew symmetric matrix for cross product operations
  src/smsfusion/_vectorops.py
  tests/test_vectorops.py
Labels: feature

#42 Add private function for quaternion (Schur) product
  src/smsfusion/_vectorops.py
  tests/test_vectorops.py
Labels: feature

#44 Improve docstring
  docs/reference/index.rst
  src/smsfusion/_ahrs.py
  src/smsfusion/_ins.py
  src/smsfusion/_transforms.py
  src/smsfusion/_vectorops.py
  src/smsfusion/benchmark/_benchmark.py
  src/smsfusion/noise/_noise.py
Labels: documentation
