Repository 4Subsea/smsfusion-python, pull requests merged in 2023-11, with the labels that each got.

#28 Flatten state output arrays
  src/smsfusion/_ahrs.py
  src/smsfusion/_ins.py
  tests/test_ahrs.py
  tests/test_ins.py
Labels: breaking-change

#29 Add function to calculate inverse angular transformation matrix
  src/smsfusion/_ins.py
  src/smsfusion/_transforms.py
  tests/test_transforms.py
Labels: feature

#32 Generate white noise, random walk and first-order Gauss-Markov random noise processes
  docs/reference/index.rst
  src/smsfusion/__init__.py
  src/smsfusion/_ahrs.py
  src/smsfusion/noise/__init__.py
  src/smsfusion/noise/_noise_models.py
  tests/test_noise_models.py
  tests/testdata/gauss_markov.csv
  tests/testdata/random_walk.csv
  tests/testdata/white_noise.csv
Labels: feature

#33 Generate IMU noise
  docs/reference/index.rst
  src/smsfusion/noise/__init__.py
  src/smsfusion/noise/_noise.py
  src/smsfusion/noise/_noise_models.py
  tests/test_noise.py
  tests/test_noise_models.py
  tests/testdata/IMUNoise.csv
  tests/testdata/NoiseModel_GM.csv
  tests/testdata/NoiseModel_RW.csv
Labels: enhancement

#34 Increases tolerance in unit test
  tests/test_noise.py
Labels: test

#35 Beating and chirp signal generators return the second time derivative
  src/smsfusion/benchmark/_benchmark.py
  tests/test_benchmark.py
Labels: feature

#36 General benchmark scenario signal generator
  src/smsfusion/benchmark/__init__.py
  src/smsfusion/benchmark/_benchmark.py
  tests/test_benchmark.py
Labels: feature
