Repository 4Subsea/smsfusion-python, pull requests merged in 2024-01, with the labels that each got.

#45 Add aided INS with multiplicative extended Kalman filter (MEKF)
  src/smsfusion/__init__.py
  src/smsfusion/_ins.py
  src/smsfusion/_mekf.py
  tests/test_mekf.py
Labels: feature

#46 Rename MEKF to AidedINS and deprecate old AidedINS
  src/smsfusion/__init__.py
  src/smsfusion/_ins.py
  src/smsfusion/_mekf.py
  tests/test_ins.py
  tests/test_mekf.py
Labels: breaking-change

#47 Rename input parameters for IMUNoise
  src/smsfusion/noise/_noise.py
  tests/test_ins.py
  tests/test_noise.py
Labels: breaking-change

#49 Refactor AHRS to align with INS classes
  src/smsfusion/_ahrs.py
  tests/test_ahrs.py
Labels: breaking-change

#50 Remove acceleration contribution from position propagation to align with documentation
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: enhancement

#52 Accept fs during instantiation of StrapdownINS. dt is no logner accepted in StrapdownINS.update
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: breaking-change

#51 Mandatory initial error covariance matrix
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: breaking-change

#53 Included latitude in AidedINS
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: enhancement

#54 Accept aiding variances in update
  src/smsfusion/_ins.py
  tests/test_ins.py
  tests/test_transforms.py
  tests/test_vectorops.py
Labels: enhancement

#55 Align syntax in AidedINS with documentation
  src/smsfusion/_ahrs.py
  src/smsfusion/_ins.py
  tests/test_ins.py
Labels: refactor

#56 Remove obsolete build script
  build.bat
Labels: chore

#57 Add function for calculating Allan variance
  src/smsfusion/noise/__init__.py
  src/smsfusion/noise/_allan.py
  tests/test_noise.py
Labels: feature
