Repository 4Subsea/smsfusion-python, pull requests merged in 2025-08, with the labels that each got.

#93 Reuse RNG in NoiseModel
  src/smsfusion/noise/_noise.py
  tests/test_noise.py
  tests/testdata/IMUNoise.csv
  tests/testdata/NoiseModel_GMdrift.csv
  tests/testdata/NoiseModel_RWdrift.csv
  tests/testdata/NoiseModel_nodrift.csv
Labels: breaking-change, enhancement

#95 Remove unnecessary private _standard_normal function
  src/smsfusion/noise/_noise.py
  tests/test_noise.py
Labels: refactor

#94 Cold start (initial roll and pitch calibration)
  docs/user_guide/quickstart.rst
  src/smsfusion/_ins.py
  src/smsfusion/_smoothing.py
  src/smsfusion/constants/__init__.py
  src/smsfusion/constants/_constants.py
  tests/test_ins.py
  tests/test_smoothing.py
Labels: feature
