Repository 4Subsea/smsfusion-python, pull requests merged in 2025-05, with the labels that each got.

#83 Replace Mahony-based AHRS with MEKF-based AHRS
  src/smsfusion/__init__.py
  src/smsfusion/_ahrs.py
  src/smsfusion/_ins.py
  tests/test_ahrs.py
  tests/test_ins.py
Labels: breaking-change, feature

#81 Quickstart guide
  docs/index.rst
  docs/reference/index.rst
  docs/user_guide/index.rst
  docs/user_guide/installation.rst
  docs/user_guide/quickstart.rst
  pyproject.toml
  src/smsfusion/_ins.py
Labels: documentation

#85 Add default P0 and noise parameters to INS classes
  docs/user_guide/quickstart.rst
  pyproject.toml
  src/smsfusion/_ins.py
  src/smsfusion/constants/__init__.py
  src/smsfusion/constants/_constants.py
  tests/test_constants.py
  tests/test_ins.py
Labels: enhancement

#86 Improve noise module documentation with respect to noise units
  src/smsfusion/noise/_noise.py
Labels: documentation

#87 Update default values for SMS Motion Gen 2 noise parameters to latest official
  src/smsfusion/constants/__init__.py
  src/smsfusion/constants/_constants.py
  tests/test_constants.py
  tests/test_noise.py
Labels: enhancement

#88 Use `typing.Self` to annotate methods returning `self`.
  .github/pull_request_template.md
  .github/workflows/ci.yaml
  .github/workflows/deploy_public.yaml
  pyproject.toml
  src/smsfusion/_ins.py
Labels: chore, enhancement
